name: Continous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      tag: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.releases_created}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          release-type: simple