name: Continous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      tag: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.releases_created}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          release-type: simple

  # This job will fetch the latest version of the code and copy it to the server
  # hosting the WordPress site. The job will run automatically when a push is made
  # to the main branch and the changes are in the /src directory.
  deploy:
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup SSH Key
        id: key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ONE_COM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "ONE_COM_KEY_PATH=~/.ssh/id_ed25519" >> $GITHUB_OUTPUT

      - name: Copy Files
        env:
          TARGET_HOST: ${{ secrets.ONE_COM_HOST }}
          TARGET_USERNAME: ${{ secrets.ONE_COM_USERNAME }}
          KEY_PATH: ${{ steps.key.outputs.ONE_COM_KEY_PATH }}
        run: |
          # add key to known hosts
          ssh-keyscan -t ed25519 -H "$TARGET_HOST" >> ~/.ssh/known_hosts

          # copy files to server
          bash scripts/deploy.sh "$TARGET_HOST" "$TARGET_USERNAME" "$KEY_PATH"
