name: Continous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'wordpress/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ONE_COM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "ONE_COM_KEY_PATH=~/.ssh/id_ed25519" >> $GITHUB_ENV

      - name: Copy files
        run: |
          bash scripts/deploy.sh "${{ secrets.ONE_COM_HOST }}" "${{ secrets.ONE_COM_USERNAME }}" "${{ env.ONE_COM_KEY_PATH }}" "TRUE"
