name: Continous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'wordpress/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ONE_COM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Copy files
        run: |
          SOURCE_PATH="./wordpress/wp-content/themes/highwire/*"
          TARGET_PATH="/www/wp-content/themes/highwire/"
          SERVER_KEY_PATH="~/.ssh/id_ed25519"

          bash scripts/deploy.sh "${SOURCE_PATH}" "${TARGET_PATH}" "${SERVER_KEY_PATH}"
