name: Continous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'wordpress/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files
        run: |
          SOURCE_THEME_PATH="./wordpress/wp-content/themes/highwire/*"
          TARGET_THEME_PATH="/www/wp-content/themes/highwire/"

          # copy over files to server 
          sshpass -p ${{ secrets.ONE_COM_PASSWORD }} scp -r "${SOURCE_THEME_PATH}" ${{ secrets.ONE_COM_USERNAME }}@${{ secrets.ONE_COM_HOST }}:"${TARGET_THEME_PATH}"
